services:
    _defaults:
        public: true


    numero2_storelocator.listener.storelocator.store_import:
        class: numero2\StoreLocatorBundle\EventListener\StoreLocator\StoreImportListener
        arguments:
            - '@database_connection'
            - '@contao.slug'
        tags:
            - { name: kernel.event_listener, event: contao.storelocator_store_import, priority: 0 }


    # numero2_storelocator.listener.data_container.store:
    #     class: numero2\StoreLocatorBundle\EventListener\DataContainer\StoreListener
